apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: soat-tech-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: soat-tech-deployment
  minReplicas: 2 
  maxReplicas: 10  
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  
